services:
  web:
    image: evilcat12/pet-family:1.0
    ports:
      - "8080:8080"
    depends_on:
      - postgres
      - seq
      - minio
    restart: always
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
  
  postgres:
    container_name: postgres
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: pet_family
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5434:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  mongo:
    container_name: mongo_db
    image: mongo
    ports:
      - "27017:27017"
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongoadmin
      MONGO_INITDB_ROOT_PASSWORD: mongopassword
    volumes:
      - mongo_data:/data/db
      
  seq:
    image: datalust/seq:latest
    container_name: seq
    restart: always
    environment: 
      - ACCEPT_EULA=Y
    ports:
      - "5341:5341"
        
  minio:
    container_name: minio
    image: minio/minio
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_data:/data
    command: server /data --console-address ":9001"
    restart: always
    
  nginx: 
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./backend/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - web
    restart: always
        
volumes:
  postgres-data:
  minio_data:
  mongo_data:


