// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PetFamily.Discussion.Infrastructure.Contexts;

#nullable disable

namespace PetFamily.Discussion.Infrastructure.Migrations
{
    [DbContext(typeof(WriteDbContext))]
    [Migration("20250425070704_dfgdfg")]
    partial class dfgdfg
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("discussion")
                .HasAnnotation("ProductVersion", "9.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("PetFamily.Discussion.Domain.Entities.Discussion", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.PrimitiveCollection<Guid[]>("Members")
                        .IsRequired()
                        .HasColumnType("uuid[]")
                        .HasColumnName("members");

                    b.Property<Guid>("RelationId")
                        .HasColumnType("uuid")
                        .HasColumnName("relation_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.HasKey("Id")
                        .HasName("pk_discussions");

                    b.ToTable("discussions", "discussion");
                });

            modelBuilder.Entity("PetFamily.Discussion.Domain.Entities.Message", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsEdited")
                        .HasColumnType("boolean")
                        .HasColumnName("is_edited");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<Guid>("discussion_id")
                        .HasColumnType("uuid")
                        .HasColumnName("discussion_id");

                    b.ComplexProperty<Dictionary<string, object>>("Text", "PetFamily.Discussion.Domain.Entities.Message.Text#Text", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("text");
                        });

                    b.HasKey("Id")
                        .HasName("pk_messages");

                    b.HasIndex("discussion_id")
                        .HasDatabaseName("ix_messages_discussion_id");

                    b.ToTable("messages", "discussion");
                });

            modelBuilder.Entity("PetFamily.Discussion.Domain.Entities.Message", b =>
                {
                    b.HasOne("PetFamily.Discussion.Domain.Entities.Discussion", "Discussion")
                        .WithMany("Messages")
                        .HasForeignKey("discussion_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_messages_discussions_discussion_id");

                    b.Navigation("Discussion");
                });

            modelBuilder.Entity("PetFamily.Discussion.Domain.Entities.Discussion", b =>
                {
                    b.Navigation("Messages");
                });
#pragma warning restore 612, 618
        }
    }
}
